### ISSUE TITLE
Bug in issue version when building?

### ISSUE THREAD

**Issue by vinyasHarish95** [sebp/scikit-survival-conda#2]
Hi there,

scikit-survival is available on my organizations' instance of conda-forge and the version on conda-forge is consistent with pypi (v0.19.0.post1). However, after installation via conda-forge, `conda list` reveals that version 0.0.0 is installed instead. I tried this on my working conda env (viharish_py37_v1) and creating a new conda env from scratch starting with installing scikit-survival (viharish_py310). In both versions, I see the same thing v0.0.0. When I try `conda update`, nothing happens. I checked all the package dependencies using `conda list` and everything looks ok. 

When importing it into a jupyter notebook, I see that the version is indeed 0.0.0. However, when I try using the package everything seems to work fine.

I got some help from my organization's IT and we think it might be a bug with the build process of this particular package version. We checked the metadata of the package inside my environment and can see it references the correct version there, but all the files are stored in a 0.0.0.0 parent folder structure:

```
grep “0.19” /<REDACTED>/users/viharish/.conda/envs/viharish_py37_v1/conda-meta/scikit-survival-0.19.0.post1-py310h769672d_0.json
   "url": [<internal-repo-mirror>/linux-64/scikit-survival-0.19.0.post1-py310h769672d_0.tar.bz2](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fanaconda.ices.on.ca%2Fapi%2Frepo%2Fconda-forge%2Flinux-64%2Fscikit-survival-0.19.0.post1-py310h769672d_0.tar.bz2&data=05%7C01%7Cv.harish%40mail.utoronto.ca%7C899f6f6f88bc437ae72b08daee7f07e7%7C78aac2262f034b4d9037b46d56c55210%7C0%7C0%7C638084526761481570%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6cInPfPJNeFpX0HISy9pWVk8pCxttQ3PFRfSow05xNg%3D&reserved=0),
  "version": "0.19.0.post1"
```
 
You can see in the metadata references to the version being 0.0.0.0 with the files too
 
```
"files": [
    "lib/python3.10/site-packages/scikit_survival-0.0.0.dist-info/COPYING",
    "lib/python3.10/site-packages/scikit_survival-0.0.0.dist-info/INSTALLER",
    "lib/python3.10/site-packages/scikit_survival-0.0.0.dist-info/METADATA",
   "lib/python3.10/site-packages/scikit_survival-0.0.0.dist-info/RECORD",
    "lib/python3.10/site-packages/scikit_survival-0.0.0.dist-info/REQUESTED",
    "lib/python3.10/site-packages/scikit_survival-0.0.0.dist-info/WHEEL",
    "lib/python3.10/site-packages/scikit_survival-0.0.0.dist-info/direct_url.json",
    "lib/python3.10/site-packages/scikit_survival-0.0.0.dist-info/top_level.txt"
```

I went down quite a rabbit hole trying to sort this out thinking the package wouldn't work so thought it would be good to let you know. 

Best wishes,
Vinyas

**Comment by sebp** [comment]
Thanks for the information.

I can confirm that this is the case with the conda-forge version.

When installing from my conda channel (conda install -c sebp) or pip the 
correct version is shown.

Maybe also file an issue at 
https://github.com/conda-forge/scikit-survival-feedstock/
